permalink: /:year/:month/:day/:title 

highlighter: pygments

title : Fredonia Science Center Kiosk

production_url : http://sunyfredonia.github.io/kiosk-science/

baseurl : http://sunyfredonia.github.io/kiosk-science/

timezone : America/New_York

prose:
  rooturl: '_posts'
  siteurl: 'http://sunyfredonia.github.io/kiosk-science/'
  metadata:
    _posts/maps:
      - name: "title"
        field:
          element: "text"
          label: "Slide title"
      - name: "image"
        field:
          element: "text"
          label: "URL to image"
      - name: "map"
        field:
          element: "text"
          label: "URL to map image"
      - name: "category"
        field:
          element: "hidden"
          value: "map"
